apiVersion: v1
kind: Service
metadata:
  name: smart-route
  namespace: smart-route
spec:
  selector:
    app: smart-route
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
